title: Andrey Satarin
description: null
author: 
  name: Andrey Satarin
  twitter: asatarin

theme: jekyll-theme-cayman

feed:
  path: /test-feed.xml
  posts_limit: 20

kramdown:
  strict_mode: true
  toc_levels: "1,2,3"

url: "https://asatarin.github.io" # the base hostname & protocol for the sitemap

plugins:
  - jekyll-feed
  - jekyll-sitemap

kramdown:
  strict_mode: true
